services:
  bbg-demo-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: bbg-demo-php
    environment:
      PHP_IDE_CONFIG: "serverName=bbg-demo"
      XDEBUG_SESSION: docker-server
    volumes:
      - ./:/var/www:rw
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - bbg-demo-postgres
    networks:
      - bbg-demo-network

  bbg-demo-nginx:
    image: nginx:alpine
    container_name: bbg-demo-nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bbg-demo-network

  bbg-demo-postgres:
    container_name: bbg-demo-postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_MULTIPLE_DATABASES: bbg_demo, bbg_demo_test
      POSTGRES_USER: bbg
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ CMD-SHELL, pg_isready, -U, borly, -d, root ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - bbg-demo-storage:/var/lib/postgresql/data:rw
    networks:
      - bbg-demo-network

volumes:
  bbg-demo-storage:
    name: bbg-demo-storage
    driver: local

networks:
  bbg-demo-network:
    driver: bridge
